#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAESPERE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAESPERE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "INSTALANDO SLOWDNS SSH BY MANDARIN" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "     ESTE SCRIP SE ISNTALARA EN TU VPS"
echo -e "     slowdns para tunel  DNS con SSH."
echo -e ""
echo -e "         \033[1;33mAHORA HACEMOS LA MAGIA ;v  \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "ACTUALIZANDO LISTA DE PAQUETES..."
fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "INSTALANDO Y ACTUALIZANDO PAQUETES NECESARIOS..."
install_pkgs () {
apt install screen -y
apt install cron -y
apt install iptables -y
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo -e "CONFIGURANDO IPTABLES..."
ipt_set () {
cd /etc
mv rc.local rc.local.bkp
wget https://github.com/leitura/slowdns/raw/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ATENCION A ESTA PARTE \033[1;33m"
echo ""
echo -ne "\033[1;32m AHORA DIGITE SU DOMINIO DNS DE CLOUDFLARE (NAMESERVER)\033[1;37m: "; read nameserver
cd /etc/slowdns
touch infons
echo $nameserver > infons
set_ns () {
sleep 1
wget https://raw.githubusercontent.com/gatesccn01/SLOWDNS/main/ssh/startdns 
wget https://raw.githubusercontent.com/gatesccn01/SLOWDNS/main/ssh/restartdns
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /etc/slowdns/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /etc/slowdns/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo "Verificando existência de key"
sleep 2
echo ""
echo "      Por favor aguarde...   "
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo -e "SE A ENCONTRADO UNA KEY EXISTENTE!"
sleep 1
echo ""
key () {
echo "QUE HACEMOS CREAMOS UNA NUEVA O USAMOS LA YA EXISTENTE"
echo ""
echo "[ 1 ] | SI QUIERO USAR LA EXISTENTE "
echo "[ 2 ] | ELIMINAR Y CREAR NUEVA KEY"
echo "[ 3 ] | ELIMINAR Y USAR KEY NATIVA"
echo "[ x ] | CANCELAR INSTALACION"
echo ""
echo -ne "ESCOGE UNA OPCION : " && read opcao
case $opcao in
1) Opcao1 ;;
2) Opcao2 ;;
3) Opcao3 ;;
x) OpcaoX ;;
*) "DIGITA BIEN" ; echo ; key;;
esac
}
Opcao1 () {
echo -ne "Restaurando key existente..." && sleep 2 && echo "OK!"
echo ""
echo -e "FINALIZANDO..."
finish_ist () {
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALACION FNALIZO!\033[0m"
echo ""
echo -ne "\033[1;33mTU DOMINIO NS ES:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mTU KEY ES :\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mPARA MAS INFO O MODS @LATAMSRC " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33mTU KEY SE GUARDO EN TU VPS EN LA RUTA /root/server.pub\033[0m"
echo -e "\033[1;33mGUARDALA PARA IMPORTAR A TUS OTRAS VPS EN EL FUTURO SI NO SABES COMO PREGUNTAME!\033[0m"
echo ""
read -p "Presione [Enter] para volver al menu o CTRL+C para salir"
slowdns
}
Opcao2 () {
cd
rm server.key server.pub
echo "Generando nueva  key"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALACION FINALIZO!\033[0m"
echo ""
echo -ne "\033[1;33mTU DOMINIO NS ES:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mTU KEY ES :\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mPARA MAS INFO O MODS @LATAMSRC " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33mTU KEY SE GUARDO EN TU VPS EN LA RUTA /root/server.pub\033[0m"
echo -e "\033[1;33mGUARDALA PARA IMPORTAR A TUS OTRAS VPS EN EL FUTURO SI NO SABES COMO PREGUNTAME!\033[0m"
echo ""
read -p "Presione [Enter] para volver al menu o CTRL+C para salir"
slowdns
}
Opcao3 () {
echo -e "DESCARGANDO KEY NATIVA.."
cd
rm server.key server.pub
wget https://raw.githubusercontent.com/gatesccn01/SLOWDNS/main/server.key
wget https://raw.githubusercontent.com/gatesccn01/SLOWDNS/main/server.pub
sleep 1
echo -e "Download Concluído"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALACION FINALIZO!\033[0m"
echo ""
echo -ne "\033[1;33mTU DOMINIO NS ES:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mTU KEY ES :\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mPARA MAS INFO O MODS @LATAMSRC " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33mTU KEY SE GUARDO EN TU VPS EN LA RUTA /root/server.pub\033[0m"
echo -e "\033[1;33mGUARDALA PARA IMPORTAR A TUS OTRAS VPS EN EL FUTURO SI NO SABES COMO PREGUNTAME!\033[0m"
echo ""
read -p "Presione [Enter] para volver al menu o CTRL+C para salir"
slowdns
}
OpcaoX () {
exit
}
key
else
echo -e "TU VPS ESTA LIMPIA AHORA QUE HACEMOS"
echo ""
key_gen () {
echo "COMO DESEAS OPTENER TU KEY"
echo ""
echo "[ 1 ] | GENERAR UNA NUEVA "
echo "[ 2 ] | USAR KEY NATIVA"
echo "[ x ] | CANCELAR INSTALACION"
echo ""
echo -ne "Digite una opcion: " && read opc_key
case $opc_key in
1) opc_key1 ;;
2) opc_key2 ;;
x) opc_keyx ;;
*) "Comando Desconocido" ; echo ; key_gen;;
esac
}
opc_key1 () {
echo "Generado su key..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALACION FINALIZO!\033[0m"
echo ""
echo -ne "\033[1;33mTU DOMINIO NS ES:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mTU KEY ES :\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mPARA MAS INFO O MODS @LATAMSRC " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33mTU KEY SE GUARDO EN TU VPS EN LA RUTA /root/server.pub\033[0m"
echo -e "\033[1;33mGUARDALA PARA IMPORTAR A TUS OTRAS VPS EN EL FUTURO SI NO SABES COMO PREGUNTAME!\033[0m"
echo ""
read -p "Presione [Enter] para volver al menu o CTRL+C para salir"
slowdns
}
opc_key2 () {
echo -e "DESCARGANDO KEY NATIVA.."
cd
wget https://raw.githubusercontent.com/gatesccn01/SLOWDNS/main/server.key
wget https://raw.githubusercontent.com/gatesccn01/SLOWDNS/main/server.pub
sleep 1
echo -e "Descarga terminada"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALACION FINALIZO!\033[0m"
echo ""
echo -ne "\033[1;33mTU DOMINIO NS ES:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mTU KEY ES :\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mPARA MAS INFO O MODS @LATAMSRC " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33mTU KEY SE GUARDO EN TU VPS EN LA RUTA /root/server.pub\033[0m"
echo -e "\033[1;33mGUARDALA PARA IMPORTAR A TUS OTRAS VPS EN EL FUTURO SI NO SABES COMO PREGUNTAME!\033[0m"
echo ""
read -p "Presione [Enter] para volver al menu o CTRL+C para salir"
slowdns
}
opc_keyx () {
echo "Abortando Instalacion"
sleep 2
slowdns
}
key_gen
fi
